//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MD_MVCEntities : DbContext
    {
        public MD_MVCEntities()
            : base("name=MD_MVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estatu> Estatus { get; set; }
        public virtual DbSet<Condicione> Condiciones { get; set; }
        public virtual DbSet<Orden> Ordens { get; set; }
        public virtual DbSet<Orden_Detalle> Orden_Detalle { get; set; }
        public virtual DbSet<Orden_Tipo> Orden_Tipo { get; set; }
        public virtual DbSet<Persona> Personas { get; set; }
        public virtual DbSet<Persona_Tipo> Persona_Tipo { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<Producto_Tipo> Producto_Tipo { get; set; }
        public virtual DbSet<Tasa_Impuesto> Tasa_Impuesto { get; set; }
        public virtual DbSet<v_Orden> v_Orden { get; set; }
        public virtual DbSet<v_Orden_Completa> v_Orden_Completa { get; set; }
        public virtual DbSet<v_Persona> v_Persona { get; set; }
        public virtual DbSet<v_Producto> v_Producto { get; set; }
    }
}
