//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Producto
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public decimal Cantidad { get; set; }
        public string Descripcion { get; set; }
        public decimal Precio { get; set; }
        public decimal Costo { get; set; }
        public byte Id_Impuesto { get; set; }
        public string Descripcion_Impuesto { get; set; }
        public string Leyenda { get; set; }
        public decimal Tasa { get; set; }
        public byte Id_Tipo { get; set; }
        public string Tipo_Descripcion { get; set; }
        public int Id_Estatus { get; set; }
        public string Estatus_Descripcion { get; set; }
    }
}
